// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# This complex type identifies an eBay user<!-- by either their <b>maskedUsername</b> or their full <b>username</b>-->
public type User record {
    # The masked user name is a user name that has certain characters hidden for privacy of the user.<!-- This field is populated only when the full user name cannot be used.-->
    string maskedUsername?;
};

# Represents the Queries record for the operation: findEligibleItems
public type FindEligibleItemsQueries record {
    # This query parameter specifies the number of results to skip in the result set before returning the first result in the paginated response.  <br><br>Combine <b>offset</b> with the <b>limit</b> query parameter to control the items returned in the response. For example, if you supply an <b>offset</b> of <code>0</code> and a <b>limit</b> of <code>10</code>, the first page of the response contains the first 10 results from the complete list of items retrieved by the call. If <b>offset</b> is <code>10</code> and <b>limit</b> is <code>20</code>, the first page of the response contains items 11-30 from the complete result set. <br><br><b>Default:</b> 0
    string offset?;
    # This query parameter specifies the maximum number of items to return from the result set on a page in the paginated response.<br><br><b>Minimum:</b> 1<br><br><b>Maximum:</b> 200<br><br><b>Default: </b>10
    string 'limit?;
};

# A complex type that describes the value of a monetary amount as represented by a global currency
public type Amount record {
    # The base currency applied to the <b>value</b> field to establish a monetary amount.  <br><br>The currency is represented as a 3-letter <a href="http://www.currency-iso.org/en/home/tables/table-a1.html" title="www.currency-iso.org" target="_blank">ISO4217</a> currency code. For example, the code for the Canadian Dollar is <code>CAD</code>.  <br><br><b>Default:</b> The default currency of the eBay marketplace that hosts the listing. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/negotiation/types/bas:CurrencyCodeEnum'>eBay API documentation</a>
    string currency?;
    # The monetary amount in the specified <b>currency</b>
    string value?;
};

# A listing that is eligible for a seller-initiated offer to a buyer.  <br><br>Listings are identified by a <b>listingId</b> value that is generated and assigned by eBay when a seller lists an item using the Trading API.  <br><br><b>Note:</b> The Negotiation API does not currently support listings that are managed with the Inventory API
public type EligibleItem record {
    # The unique eBay-assigned ID for an eBay listing.  <br><br>A <b>listingId</b> is assigned by eBay when a seller creates a listing with the Trading API
    string listingId?;
};

# This complex type defines a collection of listings that are eligible for an offer to a buyer
public type PagedEligibleItemCollection record {
    # The URI for the following page of results. This value is returned only if there is an additional page of results to display from the result set. <br><br><b>Max length</b>: 2048
    string next?;
    # The total number of items retrieved in the result set.  <br><br>If no items match the search criteria, the server returns the HTTP status code <br><code>204 No Content</code>
    int:Signed32 total?;
    # The number of results skipped in the result set before listing the first returned result. This value can be set in the request with the <b>offset</b> query parameter. <p class="tablenote"><strong>Note: </strong>The items in a paginated result set use a zero-based list where the first item in the list has an offset of <code>0</code>.</p>
    int:Signed32 offset?;
    # The URI for the preceding page of results. This value is returned only if there is a previous page of results to display from the result set. <br><br><b>Max length</b>: 2048
    string prev?;
    # The number of items returned on a single page from the result set. This value can be set in the request with the <b>limit</b> query parameter
    int:Signed32 'limit?;
    # The URI of the current page of results from the result set
    string href?;
    # A list of items that are eligible for a seller-initiated offer to a buyer.  <br><br>Each element in the list contains the listing ID<!-- <i>or</i> the SKU value--> of a listed item. These IDs represent the listings for which buyers have shown an interest
    EligibleItem[] eligibleItems?;
};

# This complex type contains the fields needed to create an offer to a buyer that is initiated by the seller
public type SendOffersRequest record {
    # If set to <code>true</code>, the buyer is allowed to make a counter-offer to the seller's offer.  <br><br><span class="tablenote"><b>Note:</b> Currently, you must set this field to <code>false</code>; counter-offers are not supported in this release.</span>  <br><br><b>Default:</b> <code>false</code>
    boolean allowCounterOffer?;
    # An array of objects where each object contains the details of an offer and the ID of the listing on which the offer is being made.  <br><br>Note that the service does not currently support the creation of multiple offers with a single call to <b>sendOfferToInterestedBuyer</b>. With this, each request can target only one listing at a time and you must populate this array with a single element that contains the details of one offer
    OfferedItem[] offeredItems?;
    # A complex type that specifies a period of time using a specified time-measurement unit
    TimeDuration offerDuration?;
    # A seller-defined message related to the offer being made.  <br><br>This message is sent to the list of "interested" buyers.  <br><br>To increase the conversion rate of the offers a seller makes to buyers, eBay recommends you always add a customized message to your offers.  <br><br><b>Maximum length:</b> 2,000 characters
    string message?;
};

# Represents the Headers record for the operation: sendOfferToInterestedBuyers
public type SendOfferToInterestedBuyersHeaders record {
    # The eBay marketplace on which your listings with "eligible" buyers appear.  <br><br>For a complete list of supported marketplaces, see <a href="/api-docs/sell/negotiation/overview.html#requirements" title="Negotiation API Overview">Negotiation API requirements and restrictions</a>
    @http:Header {name: "X-EBAY-C-MARKETPLACE-ID"}
    string xEBAYCMARKETPLACEID;
    # This header indicates the format of the request body provided by the client. Its value should be set to <b>application/json</b>. <br><br> For more information, refer to <a href="/api-docs/static/rest-request-components.html#HTTP" target="_blank ">HTTP request headers</a>
    @http:Header {name: "Content-Type"}
    string contentType;
};

# A complex type that defines an offer that a seller makes to eligible buyers
public type Offer record {
    # If set to <code>true</code>, the buyer is allowed to make a counter-offer to the seller's offer
    boolean allowCounterOffer?;
    # The type of offer being made. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/negotiation/types/api:OfferTypeEnum'>eBay API documentation</a>
    string offerType?;
    # The date and time when the offer was last modified.  <br><br>The returned timestamp is formatted as an <a href="http://www.iso.org/iso/home/standards/iso8601.htm" target="_blank">ISO 8601</a> string
    string lastModifiedDate?;
    # The list of items associated with the offer. <br><br>Currently, the offer list is restricted to a single offer
    OfferedItem[] offeredItems?;
    # A complex type that specifies a period of time using a specified time-measurement unit
    TimeDuration offerDuration?;
    # A unique eBay-assigned identifier for the offer
    string offerId?;
    # The date and time when the seller's offer was created.  <br><br>The returned timestamp is formatted as an <a href="https://www.iso.org/iso-8601-date-and-time-format.html" title="https://www.iso.org" target="_blank">ISO 8601</a> string, which is based on the 24-hour Coordinated Universal Time (UTC) clock.  <br><br><b>Format:</b> <code>[YYYY]-[MM]-[DD]T[hh]:[mm]:[ss].[sss]Z</code> <br><b>Example:</b> <code>2018-08-20T07:09:00.000Z</code>
    string creationDate?;
    # A seller-defined message related to the offer being made. This message is sent to the list of "interested" buyers along with the offer message from eBay
    string message?;
    # The eBay <b>UserName</b> of the user (seller) who initiated the offer
    string initiatedBy?;
    # The current state, or status, of an offer.  <br><br>Status states include <code>PENDING</code>, <code>COUNTERED</code>, <code>ACCEPTED</code>, and <code>DECLINED</code>. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/negotiation/types/api:OfferStatusEnum'>eBay API documentation</a>
    string offerStatus?;
    # This complex type identifies an eBay user<!-- by either their <b>maskedUsername</b> or their full <b>username</b>-->
    User buyer?;
    # A unique, eBay-assigned ID for the revision of the offer
    string revision?;
};

# OAuth2 Refresh Token Grant Configs
public type OAuth2RefreshTokenGrantConfig record {|
    *http:OAuth2RefreshTokenGrantConfig;
    # Refresh URL
    string refreshUrl = "https://api.ebay.com/identity/v1/oauth2/token";
|};

# A complex type that specifies a period of time using a specified time-measurement unit
public type TimeDuration record {
    # A time-measurement unit that specifies a singular period of time.  <br><br>A span of time is defined when you apply the value specified in the <b>value</b> field to the value specified for <b>unit</b>.  <br><br>Time-measurement units can be YEAR, MONTH, DAY, and so on. See <b>TimeDurationUnitEnum</b> for a complete list of possible time-measurement units. For implementation help, refer to <a href='https://developer.ebay.com/api-docs/sell/negotiation/types/bas:TimeDurationUnitEnum'>eBay API documentation</a>
    string unit?;
    # An integer that represents an amount of time, as measured by the time-measurement unit specified in the <b>unit</b> field
    int:Signed32 value?;
};

# A complex type that defines the offer being made to an "interested" buyer
public type OfferedItem record {
    # This value denotes the percentage that the listing in the offer will be discounted from its original listed price.  <br><br>The seller can specify either the exact price of the discounted items with the <b>price</b> field or they can use this field to specify the percentage that the listing will be discounted, but not both.  <br><br><b>Minimum:</b> <code>5</code>  <br><br><i>Required if</i> you do not specify a <b>price</b> value
    string discountPercentage?;
    # This integer value indicates the number of items in the eBay listing for which the offer is being made.  <br><br>The offer being made by the seller is an "all or nothing" offer, meaning the buyer must purchase the indicated quantity of items in order to receive the discount on the transaction.  <br><br><b>Default:</b> <code>1</code>
    int:Signed32 quantity?;
    # A complex type that describes the value of a monetary amount as represented by a global currency
    Amount price?;
    # This value is a unique eBay-assigned ID that identifies the listing to which the offer pertains.  <br><br>A <b>listingId</b> value is generated by eBay when you list an item with the Trading API.<!--  <br><br><i>Required if</i> you do not specify an <b>sku</b> value.-->
    string listingId?;
};

# Represents the Headers record for the operation: findEligibleItems
public type FindEligibleItemsHeaders record {
    # The eBay marketplace on which you want to search for eligible listings. <br><br>For a complete list of supported marketplaces, see <a href="/api-docs/sell/negotiation/overview.html#requirements" title="Negotiation API Overview">Negotiation API requirements and restrictions</a>
    @http:Header {name: "X-EBAY-C-MARKETPLACE-ID"}
    string xEBAYCMARKETPLACEID;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    http:BearerTokenConfig|OAuth2RefreshTokenGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};

# The response object returned from a <b>SendOfferToInterestedBuyers</b> request
public type SendOffersResponse record {
    # The <b>offers</b> container returns a list of the offers sent to buyers who have shown an interest in listings included in the offer
    Offer[] offers?;
};
